name: CraftGPT
version: '${project.version}'
main: com.poperie.craftgpt.CraftGPT

commands:
  tokens:
    description: Manage tokens
    usage: /tokens
  buy:
    description: Buy tokens
    usage: /buy
  ask:
    description: Ask a question
    usage: /ask <token amount> <question>